version: '3.9'

services:
################### DISCOVERY SERVER ( eureka) ###################
  discovery_service :
    container_name: serviceregistry
    build: /eureka_server
    ports:
     - "8761:8761"
    hostname: serviceregistry
    image: erueka_service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/

 ################### GATEWAY SERVER  ###################
  gateway_service :
    container_name: gateway_server
    build: /gateway-service
    ports:
     - "8089:8089"
    image: gateway_service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/     

################### MICROSERVICES ###################
  customer_reviewer_service:
    container_name: customer_reviewer_container
    build: /ms_customer_review
    environment:
      - spring.datasource.url=jdbc:mysql://docker-mysql_1:3306/hotelManagement?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
    ports:
     - "8082:8082"
    image: customer_review
    depends_on:
      - discovery_service
      - docker-mysql_1

  ms_auth:
    container_name: ms_auth_container
    build:
      context: ./ms_user_management  # Set the context to the directory containing your Dockerfile
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=docker-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=ms_auth_DB
      - EUREKA_HOST=serviceregistry
      - EUREKA_PORT=8761
      - EUREKA_SEVERPATH=/eureka/apps
    ports:
      - '7000:7000'
    image: ms_auth
    depends_on:
      - discovery_service
      - docker-postgres

  saff_management_service:
    build: /ms_saff_management
    environment:
      - spring.datasource.url=jdbc:mysql://docker-mysql_2:3307/hotelManagement?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
    ports:
     - "8086:8086"
    image: saff_management
    depends_on:
      - discovery_service
      - docker-mysql_2
  

################### DATABASES ###################

  docker-mysql_1:
    container_name: mariadb_mysql_database
    image: "mariadb:latest"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=hotelManagement
    ports:
      - 3306:3306

  docker-mysql_2:
    image: "mariadb:latest"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=hotelManagement
    ports:
      - 3307:3307   

  docker-postgres:
    container_name: postgres_database
    image: postgres
    ports:
      - 5432:5432  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ms_auth_DB
